[package]
name = "vgmms"
version = "0.1.0"
authors = ["anteater"]
edition = "2018"

[dependencies]
vgtk = { git = "https://github.com/nt8r/vgtk/", branch="patch-1" }
pretty_env_logger = "0.4"
pango = "0.8"
futures = "*"
dbus = "0.8"
